README.md
Fixed issue where Azure/compute/azurerm module was called instead of Azure/network/azurerm
=> Fixed issue with second example

main.tf
Add vm_hostname to the name of each nic interface for more comprehension.
=> Add vm_hostname to nic interface name for more comprehension

main.tf, variables.tf
Add vm_hostname to os_disk name for more comprehension in Azure GUI.
=> Add vm_hostname to os_disk name

main.tf, outputs.tf, variables.tf
Allow to don't add public ip on machine.
=> Allow not use public ip

main.tf
prefix nsg name with vm_hostname
=> Fix nsg name

main.tf
- Split `account_type` variable into two variables
- Add mandatory `os_profile_windows_config`
=> Use azurerm v0.3.0

main.tf
Don't assume WindowsServer is the only offer for which Windows VMs are appropriate, and short-circuit this logic if the windows image parameter is explicitly specified.
=> Resolve issue #56

README.md, variables.tf
https://github.com/Azure/terraform-azurerm-compute/issues/87
=> updated var and readme for windows vm example

os/variables.tf
added new version strings for CentOS and RHEL
=> bumb os version

README.md, test/fixture/main.tf
I have shortened the hostname in fixture test to fix the CI
=> Fix CI test

README.md, main.tf, os/variables.tf, outputs.tf, test/fixture/main.tf, test/fixture/terraform.tfvars, test/fixture/variables.tf, variables.tf
1. allow custom location for the module:
fix :https://github.com/Azure/terraform-azurerm-compute/issues/133
https://github.com/Azure/terraform-azurerm-compute/issues/125
2. fix readme examples:
fix: https://github.com/Azure/terraform-azurerm-compute/issues/128
3. fix vm_os_simple count condition:
fix: https://github.com/Azure/terraform-azurerm-compute/issues/126
4. export availability zone of the vms:
fix:https://github.com/Azure/terraform-azurerm-compute/issues/91
=> Allow custom location and fix issues

variables.tf
Fix issues in comments in https://github.com/Azure/terraform-azurerm-compute/pull/137
=> Fix default value of `source_address_prefixes`

examples/complete/main.tf
=> Removing depends_on in examples code

examples/complete/override.tf.tplt, test/e2e/terraform_compute_test.go, test/upgrade/upgrade_test.go
This pull request added an override template file to example folder so the version upgrade test could work properly.
- [*] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [*] I have executed pre-commit on my machine
- [*] I have passed pr-check on my machine
=> Add override template file so we can run version upgrade test

.tflint_alt.hcl, README.md, main.tf, outputs.tf
This pr rename some resources to snake case so this module could follow the community's naming convention.
#192 
- [*] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [*] I have executed pre-commit on my machine
- [*] I have passed pr-check on my machine
=> Rename some resources to snake case.

.tflint_alt.hcl, main.tf, outputs.tf
=> Convert legacy splat syntax into bracket syntax

.tflint_alt.hcl, main.tf
Fix unused variable issue, add the missing argument back to fix the bug introduced by #189
#197 
=> Fix the bug introduced by adding `var.storage_os_disk_size_gb` back.

README.md, examples/complete/outputs.tf, outputs.tf
This pull request output vm names so we can composite this module with other modules.
#146 #145 
=> Output vm names

main.tf
Solve #107 by adding `create_before_destroy = true` to defer public ip's deletion.
Issue #107's root cause is Terraform will try to execute deletion before update, once we tried to delete the public ip, it is still attached on the network interface.
Declare this `create_before_destroy` will defer this public ip resource's deletion after creation and update so we can fix the issue.
#107 
=> Solve #107 by adding `create_before_destroy = true` to defer public ip's deletion.

.tflint_alt.hcl
=> Bump tflint plugin version, add new checking rule

README.md
We have a new alternative virtual machine module, this pull request added an introduction of this new module in the readme file.
#000
=> Update readme to recommend new virtual machine module

README.md, examples/complete/providers.tf, examples/extensions/providers.tf, versions.tf
This pr is based on #224 so thanks for @OLeonardoRodrigues. I'd like to publish a new release at 1st March so I just rewrite your pr.
#222
=> Update versions.tf to require Terraform v1.3

examples/complete/key_vault.tf
The `complete` example has been broken since this provider [feature](https://github.com/hashicorp/terraform-provider-azurerm/issues/14471) requires extra permission, this pr fixed the broken example.
#000
=> Fix broken example

.checkov_config.yaml
=> Fix checkov issue
