README.md

Remove the output variables for Terraform Module formatting. 
Thanks,
Chris

Remove Output variable from README

---

README.md

Fix the Windows Server public DNS IP example name to be valid. Otherwise you get:
```
* module.mycompute.azurerm_public_ip.vm: 1 error(s) occurred:
* azurerm_public_ip.vm: network.PublicIPAddressesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="DomainNameLabelReserved" Message="The domain name label mywindowsservers225 is invalid. The name itself or part of the name is a reserved word such as a trademark. Please use a different name." Details=[]
```

minor example fix

---

README.md

fix a couple of bugs in the usage example

fix usage example formatting

---

README.md
main.tf
variables.tf

Allow to add boot diagnostics option.

Add boot diagnostics option

---

.gitignore
main.tf
variables.tf

Add datastorage disk

---

main.tf

azurerm provider v0.3.0 introduced some incompatibles changes. So I fix the version to max 0.2.2.

Fix version to ~> 0.2.2

---

README.md
main.tf
os/outputs.tf
os/variables.tf
outputs.tf
variables.tf

- Fixes #16 
- Updates Readme for new functionality with Public IPs and boot diagnostic storage

Add NSG Update

---

variables.tf

Because the version of Terraform I'm using doesn't like it.

Add space between variable name and starting {

---

.travis.yml

- Switches Travis to use build stages to make it consistent with all the other modules and make it easier to add `rake e2e` in its own isolated and potentially parallel flow.  IF Travis eventually supports approval workflow (like CircieCI), then this would likely be pre-requisite.
- Add in `install: true` to prevent Travis from trying to do any pre-requisite install based on Gemfile in the repo since Docker handles all of this for us.

Switch Travis to build stages

---

main.tf
variables.tf

Currently there is no way to create a windows VM with the existing Module using custom images. I have added one more optional variable called is_windows_image to support the windows custom image scenario. Meanwhile I also felt that we need to avoid clashing of the variables when vm_os_id is provided and the 4 variables that define the market place. I have added logic to ignore the market place image variables when user specifies vm_os_id.

Fix custom image

---

README.md

The latest version of the network module no longer adds in nsg rules / vars, so locking to the older version of the network module until a better access solution is created.

fix network module example

---

outputs.tf

Hi,
I just modify output.tf. 
We are able to get **vm_ids** for _azurerm_virtual_machine.vm-\*-with-datadisk.\*.id_
Thanks.
Regards

add vm-with-datadisk in output.tf

---

.github/ISSUE_TEMPLATE/feature_request.md
bug_report.md

Add issue template to this repo.

Add .github for issue and feature request templates.

---

main.tf

Bumped version of provider azurerm to 1.1.0, so we can use azurerm_virtual_network_gateway and azurerm_virtual_network_gateway_connection. Closes #39.

Resolve #39: bump azurerm provider version

---

main.tf

There were several resources created by this module that were not getting tagged, this update fixes that by tagging the availability set, public ip, network security group and network interface. This should cover everything that can be tagged, but if there is anything missing, I'd be happy to update the PR. Thanks!

Tag all resources ceated by the module

---

main.tf

Resolve #71 by overriding the default false value for provision_vm_agent.

Provision vm agents for Windows machines

---

main.tf

Resolves #99, allowing use with TF 0.12.
Prior to this change, Terraform complains because of the version of the Random provider required.
```
$ terraform init
Initializing modules...
Downloading Azure/compute/azurerm 1.2.1 for VM...
- VM in .terraform/modules/VM/Azure-terraform-azurerm-compute-dbe0daa
- VM.os in .terraform/modules/VM/Azure-terraform-azurerm-compute-dbe0daa/os
Initializing the backend...
Initializing provider plugins...
- Checking for available provider plugins...
Provider "random" v1.3.1 is not compatible with Terraform 0.12.3.
Provider version 2.1.0 is the earliest compatible version. Select it with 
the following version constraint:
version = "~> 2.1"
Terraform checked all of the plugin versions matching the given constraint:
~> 1.0
Consult the documentation for this …
```

Update module dependency on Random to allow use in Terraform 0.12.3

---

main.tf
outputs.tf

This PR modifies where the security group rule is created. Before the security group rule was an inline rule in the security group resource. By using an inline rule it causes problem later if you wish to add additional rules to the security group. Basically, between terraform apply the additional rules will be added or removed. 
For convenience I also added the output `network_security_group_name` so that it can be used for additional `azurerm_network_security_rule` resources.  
```
module "cluster" {
source              = "../terraform-azurerm-compute"
nb_instances        = "1"
admin_username      = "${var.user_name}"
resource_group_name = "${var.resource_group_name}"
location            = "${var.location}"
nb_public_ip        = "1"
public_ip_dns       = ["test-cluster"]
ssh_key …
```

Move Security Group Rule to Dedicated Resource

---

.travis.yml
Dockerfile
Gemfile
README.md
main.tf

Integration of terramodtest 0.5.0
Fix example in README

Integration of terramodtest 0.5.0

---

variables.tf

set public_ip_dns default variable to null

Fixed domain_name_label must contain only lowercase alphanumeric characters, numbers and hyphens

---

main.tf
variables.tf

I would want some control on nsg security rule for remote_port:
- Create it only if remote_port is specified
- Add ability to control source IP ranges

Conditionally create nsg security rule | Parametrise source IP ranges

---

main.tf
outputs.tf

Fix https://github.com/azure/terraform-azurerm-compute/issues/149
--- PASS: TestTerraformSshExample (491.69s)
PASS

`public_ip_address` will be empty when `allocation_method` is `Dynamic`

---

README.md
main.tf
test/fixture/main.tf
variables.tf

Fixes #153 
Adding the ability of defining ssh keys as raw value either to pass it directly as string to the module or refer it from another data source

support raw value for ssh keys in addition to paths

---

main.tf

This PR makes the use of `ssh_key` optional by setting it to empty string. This is useful if somebody wants to use `ssh_key_values` only.

Allow to make ssh_key optional

---

Dockerfile
main.tf

In terraform >= 0.15.0, the deprecated list method is removed. This causes the module to stop working on newer versions. List method has been changed to tolist method.
For more information see:
- https://www.terraform.io/docs/language/functions/tolist.html
- https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md#0150-april-14-2021
Error:
```bash
│ Error: Error in function call
│ 
│   on .terraform/modules/vm_set/main.tf line 33, in resource "azurerm_virtual_machine" "vm-linux":
│   33:   count                         = ! contains(list(var.vm_os_simple, var.vm_os_offer), "WindowsServer") && ! var.is_windows_image ? var.nb_instances : 0
│     ├────────────────
│     │ var.vm_os_offer is a string, known only after apply
│     │ var.vm_os_simple is a string, known only after apply
│ …
```

Fixed deprecated list method

---

main.tf

Repacing location and resource_group_name with local variables

---

main.tf

When attempting to use a marketplace image, the terraform apply will currently fail with:
> │ Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'The offer with Offer ID '8-gen1' was not 
> found. Try one of these: 1- Make sure the offer name is written correctly. 2- If this offer was recently created, allow up to 30 minutes for it to be available for purchase. 3- The offer may have been removed from the marketplace. Look for similar offers from this p
> ublisher here: 'https://azuremarketplace.microsoft.com/en-us/marketplace/apps?page=1%26search=almalinux%208-gen1'. Publisher ID: 'almalinux', Offer ID: '8-gen1', …

Adjust the "plan" input to properly set the image name and product

---

test/unit/terraform_compute_test.go

We have a classic `foreach` error in our go test code, it would cause randomly error when we try to execute tests concurrently, this pull request capture the iterator variable into a local variable to avoid such error.

Pin the iterator variable to avoid concurrent test error

---

examples/complete/main.tf
locals.tf
main.tf
test/unit/terraform_compute_test.go
unit-fixture/outputs.tf

This pull request added unit tests and `precondition` check logic for separate data disk logic.
The pr also change data disk list generation logic in `locals.tf`, we've removed `var.vm_hostname` from map's key so we can use this map with `for_each` when `var.vm_hostname` is generated from another resource, like random.
This pr is an amendment to #227.

Improve separate data disk resource logic

---

CHANGELOG.md
main.tf

The error below appear when `length(azurerm_public_ip.vm[*].id) = 0`
```
╷
│ Error: parsing Azure ID: parse "": empty url
│ 
│   with module.vms["aiola"].azurerm_network_interface.vm[0],
│   on .terraform/modules/vms/main.tf line 446, in resource "azurerm_network_interface" "vm":
│  446:     public_ip_address_id = length(azurerm_public_ip.vm[*].id) > 0 ? element(concat(azurerm_public_ip.vm[*].id, tolist([
│  447:       ""
│  448:     ])), count.index) : ""
│ 
╵
```
* Change `azurerm_public_ip` to null instead of empty string.

Fix broken ip_configuration when azurerm_public_ip is null
